FROM pandoc/core:2.13
RUN \
 apk update && \
 apk add --no-cache \
  ttf-dejavu \
  librsvg-dev \
  texlive-xetex \
  texlive \
  texlive-xetex \
  texmf-dist \
  texmf-dist-formatsextra \
  texmf-dist-latexextra \
  texmf-dist-pictures \
  texmf-dist-science
# RUN tlmgr install fontawesome
